### Adicionar Produtos
POST http://localhost:3003/products/create
Content-Type: application/json

{
    "name": "Taco de Golfe",
    "tags": ["esporte, grife, golfe"]
}

### Pegar todos os produtos / definir parâmetro
GET http://localhost:3003/products

### Pegar produto pelo ID
GET http://localhost:3003/products/search/a6ca4191-2bab-4a59-88dc-5f94f41aa219