### Adicionar Produtos
POST http://localhost:3003/products/create
Content-Type: application/json

{
    "name": "Taco de Golfe",
    "tags": ["esporte, grife, golfe"]
}

### Pegar todos os produtos / definir parâmetro
GET http://localhost:3003/products?search=jaqueta