POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "teste",
    "email": "miguel@mite.com",
    "password": "kkk",
    "role": "seila"
}

###

POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "miguelmiguel",
    "password": "admin"
}

###