
//Endpoints de Usuário
### Cadastro
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "teste",
    "email": "teste@teste.com",
    "password": "123"
}

### Login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "miguel@miguel.com",
    "password": "admin"
}

### Criar Usuário (ADMIN)
POST http://localhost:3003/users/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFmMzQ3NmVkLTM1NDMtNDRjMS1iOWU3LWFhOWZiZjFlNjUwZCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2NDA2ODAyMywiZXhwIjoxNjY0MDg2MDIzfQ.hTQ_pycNBjM5Iwri7q7mm2KM4QKQSHbWwc0pM9rG7Fw
Content-Type: application/json

{
    "name": "teste",
    "email": "teste@teste.com",
    "password": "123",
    "role": "admin"
}

### Pegar Todos Os Usuários (ADMIN)
GET http://localhost:3003/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFmMzQ3NmVkLTM1NDMtNDRjMS1iOWU3LWFhOWZiZjFlNjUwZCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2NDM1ODUzNywiZXhwIjoxNjY0Mzc2NTM3fQ.M_KAsT2k5mlVN9ONT4BqpSx45v00Qd0nVstJY7N0t08

### Editar Usuário (ADMIN)
PUT  http://localhost:3003/users/edit/fcd30617-e705-4994-a4e5-21e128a89b01
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFmMzQ3NmVkLTM1NDMtNDRjMS1iOWU3LWFhOWZiZjFlNjUwZCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2NDQwMDg3NywiZXhwIjoxNjY0NDE4ODc3fQ.nZtwHwNuoNtOPt31n4oQY3FTnFqncWoSYimpxSWgtnA
Content-Type: application/json

{
"name": "teste",
"password": "123"
}

### Deletar Usuário (ADMIN)
DELETE http://localhost:3003/users/delete/a0f66358-eb5f-4f70-874d-7ce7034a1c85
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFmMzQ3NmVkLTM1NDMtNDRjMS1iOWU3LWFhOWZiZjFlNjUwZCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2NDQwMDg3NywiZXhwIjoxNjY0NDE4ODc3fQ.nZtwHwNuoNtOPt31n4oQY3FTnFqncWoSYimpxSWgtnA



/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////



//Endpoints de Playlist
### Criar Playlist
POST http://localhost:3003/playlists/create/af3476ed-3543-44c1-b9e7-aa9fbf1e650d
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFmMzQ3NmVkLTM1NDMtNDRjMS1iOWU3LWFhOWZiZjFlNjUwZCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2NDM5ODIxNiwiZXhwIjoxNjY0NDE2MjE2fQ.S2bkNa_SyeQx4Nm3sI7bIFoAtIKtPbIOAdCh54G3S68
Content-Type: application/json

{
    "name": "Basilidade",
    "genre": "MPB",
    "musics": "Burguesinha, Por Você, Partilhar"
}

### Pegar Todas Playlists
GET http://localhost:3003/playlists/a0f66358-eb5f-4f70-874d-7ce7034a1c85
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEwZjY2MzU4LWViNWYtNGY3MC04NzRkLTdjZTcwMzRhMWM4NSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNjY0Mzk5NDMzLCJleHAiOjE2NjQ0MTc0MzN9.4T8rseRsoFWmxWnSd8d3IWA87EbJoky3NB5MiffKxBM

###Editar Playlist
PUT http://localhost:3003/playlists/edit/a0f66358-eb5f-4f70-874d-7ce7034a1c85

### Deletar Playlist
DELETE http://localhost:3003/playlists/delete/af3476ed-3543-44c1-b9e7-aa9fbf1e650d/3131afdf-3721-4df1-bddb-edaacb87bfb0
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFmMzQ3NmVkLTM1NDMtNDRjMS1iOWU3LWFhOWZiZjFlNjUwZCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2NDUwODgwNCwiZXhwIjoxNjY0NTI2ODA0fQ.eD2Gz9lfPQDR_0e5P9OR1Mi6XeAzsbooVYG0MasJLXI
